### PR TITLE
Add publication RR-9564

### PR DESCRIPTION
**Pull request by claudemarche**
Add a new publication, and also add a field "wherepublished" to tell where a publication appeared

### CODE REVIEW

**Comment by claudemarche** [comment]
Notice that I did not check if the production of the Web site is OK.

**Comment by RadioPotin** [comment]
Hi, thanks for your contribution, I'll get to the review and integration very soon!

**Review by RadioPotin — COMMENTED** [review]
Despite this slight oversight with the French version of that page, everything seems in order, I'll manage a merge process as soon as you're done!

Thank for your contribution.

**Comment by RadioPotin** [comment]
Nevermind, I got to adding my two suggestions myself so no need to worry about it!

**Review by RadioPotin — APPROVED** [review]
This is definitely mergeable

**Pull request merged**
