### PR TITLE
Add Blog page, proper bilingual support, proper thumbnail handing in article excerpts

### LINKED ISSUE #4: Ajouter un onglet Blog/Actualités
... pour pouvoir afficher facilement des news sur l'avancement du projet.

### PR DESCRIPTION
**Pull request by RadioPotin**
This should fix #4

I have also provided the first article of the blog, about the kickoff of the project.

I've yet to add the specific image of the article to its page and this should be mergeable quite soon

### CODE REVIEW

**Comment by RadioPotin** [comment]
Fixes #6 too

**Comment by RadioPotin** [comment]
Okay so the first big batch of structure and content is done for the website.

There are still a few places on it where a few links could be useful, and many CSS issues to be made, which i will both engage with next.
I have not yet undertaken the documentation effort I had planed initially so keep an eye out for that in the upcoming PRs

Waiting for review on [here](https://radiopotin.github.io/website/fr/)

**Comment by Ninjapouet** [comment]
You should add TIS analyser for Guillaume sent its description.

**Review by Ninjapouet — APPROVED** [review]
Suffisant pour le moment. Le look'n'feel sera modifié au fil de l'eau.

**Pull request merged**
